[package]
name = "music-chat-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
playlist_handler = { version = "0.1.0", path = "playlist-handler" }
messages_scraper = { version = "0.1.0", path = "messages-scraper" }
log = "0.4.14"
env_logger = "0.11.0"