[package]
name = "music-chat-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
rspotify = { version = "0.12.0", features = ["env-file", "cli"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
