[package]
name = "messages_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
log = "0.4"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
select = "0.5"
regex = "1.5"
scraper = "0.13"
env_logger = "0.11.0"
tempfile = "3.10.1"
